src/components/SidebarContent/__tests__/SidebarContent.test.tsx

chore: update SidebarContent.test.tsx

---

android/app/build.gradle
ios/PocketPal.xcodeproj/project.pbxproj
package.json

chore: bump version

---

.github/workflows/release.yml
android/fastlane/Fastfile

Keystore path updated to be consistent with current codebase and the ci

fix(ci): update keystore path

---

.github/workflows/release.yml

correct env var for gradle! Use the ones from build.gradle.

fix(ci): correct env var for gradle

---

.github/workflows/release.yml
android/fastlane/Fastfile

Gradle env variable are not applied correctly, moving builds to fastlane

fix(ci): move apk build to fastlane

---

android/fastlane/Fastfile

fix(ci): remove build type from task name

---

android/fastlane/Fastfile

Skip upload apk for upload_to_play_store

fix(ci): skip upload apk for upload_to_play_store

---

.github/workflows/release.yml

Set the version in ci to env and use in the subsequent steps - in build_android.

chore(ci): set version to env

---

ios/PocketPal.xcodeproj/project.pbxproj
ios/Podfile
ios/Podfile.lock
jest/fixtures/models.ts
package.json
src/screens/BenchmarkScreen/BenchResultCard/BenchResultCard.tsx
src/screens/BenchmarkScreen/BenchmarkScreen.tsx
src/screens/BenchmarkScreen/DeviceInfoCard/DeviceInfoCard.tsx
src/screens/BenchmarkScreen/styles.ts
src/screens/ModelsScreen/CompletionSettings/CompletionSettings.tsx
src/screens/ModelsScreen/CompletionSettings/__tests__/CompletionSettings.test.tsx
src/screens/SettingsScreen/SettingsScreen.tsx
src/utils/chat.ts
src/utils/l10n.ts
src/utils/modelSettings.ts
yarn.lock

Sync llama.rn -> llama.cpp
Fixes #133

[Feat] sync llama.cpp

---

android/gradle/wrapper/gradle-wrapper.properties

The checksum is needed for F-Droid submission: https://github.com/a-ghorbani/pocketpal-ai/issues/55#issuecomment-2548875661
Closes #146

chore: add SHA-256 checksum to Gradle wrapper properties

---

App.tsx
ios/Podfile.lock
package.json
src/components/SidebarContent/SidebarContent.tsx
src/screens/TestCompletionScreen/TestCompletionScreen.tsx
src/screens/TestCompletionScreen/index.ts
src/screens/TestCompletionScreen/styles.ts
src/screens/index.ts
src/utils/chat.ts
yarn.lock

This PR syncs llama.cpp (to support Gemma 3)
Fixes #235

Feat: sync llama.cpp

---

ios/Podfile.lock
package.json
src/screens/TestCompletionScreen/TestCompletionScreen.tsx
yarn.lock

Sync llama.rn/llama.cpp.
Fixes #240

fix(android): sync llama.cpp to fix long text generation issue

---

src/utils/l10n.ts

This PR enhances the Japanese localization by improving the natural expression and consistency of translations. The changes focus on making the text more idiomatic and user-friendly for native Japanese speakers while maintaining technical accuracy.
Changes include:
- Refined phrasing for better cultural context
- Improved consistency in terminology
- More natural UI language for Japanese users
- Fixed awkward expressions and technical terms
- Ensured consistent tone throughout the application

Improve Japanese localization for better natural expression

---

src/utils/l10n.ts

This PR improves Japanese localization, thanks to @lnkiai

chore(l10n): improve Japanese translations

---

src/hooks/useChatSession.ts
src/services/downloads/DownloadManager.ts

Some devices experienced missing or duplicated tokens during text generation, likely due to race conditions in the token buffer management.
This PR replaces throttled buffer approach with time-based batch processing to prevent missing or duplicated tokens during generation. Tokens are accumulated for 100ms and then processed in a single batch.
Fixes #300

Fix: missing/duplicated tokens during text generation

---

__mocks__/services/downloads.ts
__mocks__/stores/modelStore.ts
src/components/ChatPalModelPickerSheet/ChatPalModelPickerSheet.tsx
src/components/ChatPalModelPickerSheet/__tests__/ChatPalModelPickerSheet.test.tsx
src/components/PalsSheets/ModelNotAvailable.tsx
src/components/SkillsDisplay/SkillsDisplay.tsx
src/components/SkillsDisplay/styles.ts
src/screens/ModelsScreen/ModelCard/ModelCard.tsx
src/screens/ModelsScreen/ModelCard/__tests__/ModelCard.test.tsx
src/screens/ModelsScreen/ModelsScreen.tsx
src/store/ModelStore.ts
src/store/__tests__/ModelStore.test.ts
src/utils/l10n.ts

Fixes deafault mmproj automatic download.

Fix: automatic mmproj download

---

src/components/HeaderLeft/styles.ts
src/components/SendButton/SendButton.tsx
src/components/StopButton/StopButton.tsx
src/hooks/__tests__/useMemoryCheck.test.ts
src/hooks/useChatSession.ts
src/hooks/useMemoryCheck.ts
src/screens/ModelsScreen/HFModelSearch/DetailsView/DetailsView.tsx
src/screens/ModelsScreen/HFModelSearch/DetailsView/ModelFileCard/ModelFileCard.tsx
src/screens/ModelsScreen/ModelCard/ModelCard.tsx
src/store/ModelStore.ts
src/utils/chat.ts

Resolves a couple of issues. 
- remove system prompt from smolvlm
- uses model size in useMemoryCheck and memoizes converted model (from hf) in model card to prevent rerenders. 
Fixes #331

Fix: a few bug fixes

---

src/hooks/useChatSession.ts

The first message sent in a chat session was appearing twice when sent to llama.rn.
Fixes #363

Fix: chat message duplication issue in useChatSession

---

ios/Podfile.lock
package.json
yarn.lock

This PR upgrades llama.rn (=> syncs llama.cpp) to support SmolLM3
Fixes #367

feat: upgrade llama.rn (hence llama.cpp) to support SmolLM3

---

ios/Podfile.lock
package.json
src/api/feedback.ts
src/components/ChatView/ChatView.tsx
src/components/ContentReportSheet/ContentReportSheet.tsx
src/components/ContentReportSheet/index.ts
src/components/ContentReportSheet/styles.ts
src/components/index.ts
src/screens/DevToolsScreen/screens/TestCompletionScreen/TestCompletionScreen.tsx
src/utils/chat.ts
src/utils/l10n.ts
yarn.lock

This PR upgrades llama.rn -> llama.cpp
Fixes #392

feat: upgrade llama.rn

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/pocketpalai/DeviceInfoModule.kt
ios/PocketPal/DeviceInfoModule.m
package.json
src/screens/BenchmarkScreen/DeviceInfoCard/DeviceInfoCard.tsx
src/screens/BenchmarkScreen/DeviceInfoCard/styles.ts
src/screens/SettingsScreen/SettingsScreen.tsx
src/utils/l10n.ts
src/utils/types.ts
yarn.lock

This PR adds an initial attempt to support for GPU (OpenGL) support for android (adreno). 
Fixes #444 
Fixes #194 
Fixes #196

Feat: add GPU (OpenGL) support for android (adreno)
