a-ghorbani/pocketpal-ai

- .github/workflows/ci.yml
- README.md
- src/screens/ModelsScreen/ModelSettings/__tests__/ModelSettings.test.tsx
- src/screens/ModelsScreen/__tests__/ModelsScreen.test.tsx
adding cache layer to save time of pipeline 
making jobs of build depend on job of lint and tests so if lint fail, we do not need to run pipeline
Fixes #68 
[before caching ](https://github.com/MahmoudMabrok/pocketpal-ai/actions/runs/11544281602)
[after cache ](https://github.com/MahmoudMabrok/pocketpal-ai/actions/runs/11544281602)
from **18m** as total into **13m** as total (~30% saving time)
> ci: enhance pipeline by adding cache layer

- android/app/build.gradle
- ios/PocketPal.xcodeproj/project.pbxproj
- package.json
- src/store/ModelStore.ts
- src/store/__tests__/ModelStore.test.ts
- src/store/defaultModels.ts
- src/utils/__tests__/utils.test.ts
- src/utils/index.ts
If a new parameter is introduced to the model completion settings, the parameter is not applied to the existing model unless the model list is reset. This causes an app crash when the UI tries to display the updated settings in the model card.
Fixes #75
> fix: resolve model list merge issue during app update

- android/app/build.gradle
- ios/PocketPal.xcodeproj/project.pbxproj
- package.json
- src/hooks/useChatSession.ts
- src/store/defaultModels.ts
- src/utils/__tests__/chat.test.ts
- src/utils/chat.ts
Adds SmolLM ([SmolLM2-1.7B-Instruct-Q8_0.gguf](https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF/blob/main/SmolLM2-1.7B-Instruct-Q8_0.gguf)) to the default models list.
Fixes #76
> feat: adds SmolLM

- .eslintrc.js
- src/components/ChatView/ChatView.tsx
- src/components/Input/Input.tsx
- src/components/LoadingBubble/LoadingBubble.tsx
- src/components/LoadingBubble/index.ts
- src/components/LoadingBubble/styles.ts
- src/components/TextMessage/__tests__/TextMessage.test.tsx
- src/components/index.ts
- src/hooks/useChatSession.ts
- src/screens/ChatScreen/ChatScreen.tsx
- src/screens/ModelsScreen/ModelSettings/__tests__/ModelSettings.test.tsx
- src/screens/ModelsScreen/__tests__/ModelsScreen.test.tsx
- tsconfig.json
I've added a loading indicator with three dots to show that the model is processing, providing users with feedback that something is happening. I believe this will enhance the user experience by indicating activity. This is my first open-source PR in a while, so please let me know if any changes are needed. I’m also planning to contribute more improvements.
> feat: add loading bubble on chat screen

- package.json
- src/screens/ModelsScreen/HFModelSearch/HFModelSearch.tsx
- src/screens/ModelsScreen/HFModelSearch/styles.tsx
Bottom sheet content is rendered in a portal, outside the main component tree, which breaks the theme context chain. 
By adding PaperProvider within the bottom sheets, we restore proper theming for all Paper components rendered inside them.
Fixes #96 
- Added PaperProvider within bottom sheet components to restore theme context
- Fixed background colors for bottom sheet and handle indicator
> Fix dark mode theming in bottom sheet components

- __mocks__/stores/modelStore.ts
- src/hooks/__tests__/useChatSession.test.ts
- src/hooks/useChatSession.ts
- src/utils/chat.ts
When the system prompt is undefined, the UI does not render the system prompt input text.
This pull request addresses the issue by setting the default value of the system prompt to an empty string.
Fixes #103
> fix: add empty system prompt for HF and local models

- ios/Podfile.lock
- package.json
- src/store/ModelStore.ts
- yarn.lock
Syncs llama.rn (0.4.3)
- https://github.com/mybigday/llama.rn/pull/95
- https://github.com/mybigday/llama.rn/pull/92
- https://github.com/mybigday/llama.rn/pull/91
- https://github.com/mybigday/llama.rn/pull/87
- https://github.com/mybigday/llama.rn/pull/82
Fixes #95 
Fixes #94
> feat: sync llama.rn -> llama.cpp

- jest/fixtures/models.ts
- src/screens/ModelsScreen/CompletionSettings/CompletionSettings.tsx
- src/screens/ModelsScreen/CompletionSettings/__tests__/CompletionSettings.test.tsx
- src/store/ModelStore.ts
- src/utils/chat.ts
When models are downloaded through Hugging Face search or loaded locally, the app currently infers stop words from the EOS token, but that’s not enough. EOT tokens also need to be included as stop words; otherwise, responses might contain those tokens.
This PR checks if any of these tokens:
```
'</s>',
'<|end|>',
'<|eot_id|>',
'<|end_of_text|>',
'<|im_end|>',
'<|EOT|>',
'<|END_OF_TURN_TOKEN|>',
'<|end_of_turn|>',
'<|endoftext|>',
```
are in the chat template and adds them to the stops array if found.
Also we remove `tfs_z`.
Fixes #101
> fix: add stop tokens that are in the chat template and remove tfs_z

- .github/workflows/release.yml
Added GitHub Release creation step to the release workflow to provide direct APK downloads alongside Play Store distribution. This enables easier access to app releases for beta testers and users who don't use Google Play Store.
- Added release APK build step
- Configured APK artifact upload to GitHub Releases
Related issue #55 
Related to discussion #114
> chore(ci): add GitHub release APK distribution

- .github/workflows/release.yml
Seemingly the signing config isn't being properly passed to Gradle. 
This modifies the Android build step to ensure the signing configuration is properly set using gradle params.
> fix(ci): add env var for gradle in step 10

- src/screens/BenchmarkScreen/BenchResultCard/BenchResultCard.tsx
- src/screens/BenchmarkScreen/BenchResultCard/styles.ts
- src/screens/BenchmarkScreen/BenchmarkScreen.tsx
- src/screens/SettingsScreen/SettingsScreen.tsx
- src/screens/SettingsScreen/__tests__/SettingsScreen.test.tsx
- src/screens/SettingsScreen/styles.ts
- src/store/ModelStore.ts
- src/utils/types.ts
This PR adds the following model initialization parameters to the settings page UI:
-   n_batch
-   n_ubatch
-   n_threads
-   flash_attn
-   cache_type_k
-   cache_type_v
Additionally, the benchmark results now include these metrics:
-   n_context
-   n_batch
-   n_ubatch
-   n_threads
-   flash_attn
-   cache_type_k
-   cache_type_v
-   n_gpu_layers
Fixes #79
> [Feat] Expose attn, batch, ubatch, cach_type_kv settings to the UI and bench results

- App.tsx
- __mocks__/stores/chatSessionStore.ts
- src/components/ChatView/ChatView.tsx
- src/components/ChatView/styles.ts
- src/components/Dialog/styles.ts
- src/components/Divider/styles.ts
- src/components/MarkdownView/styles.ts
- src/components/ModelsHeaderRight/ModelsHeaderRight.tsx
- src/hooks/useChatSession.ts
- src/screens/BenchmarkScreen/BenchmarkScreen.tsx
- src/screens/BenchmarkScreen/DeviceInfoCard/DeviceInfoCard.tsx
- src/screens/BenchmarkScreen/DeviceInfoCard/styles.ts
- src/screens/BenchmarkScreen/__tests__/BenchmarkScreen.test.tsx
- src/screens/BenchmarkScreen/styles.ts
- src/screens/ModelsScreen/CompletionSettings/styles.ts
- src/screens/SettingsScreen/styles.ts
- src/store/ChatSessionStore.ts
- src/utils/theme.ts
- src/utils/types.ts
This PR improves the theme and includes a new feature to improve the chat scrolling experience. It prevents auto-scrolling when the user manually scrolls. Additionally this pr adds a scroll-to-bottom button.
**Changes**:
- Improved visual themes.
- Added logic to disable auto-scrolling when the user intervenes with the scrolling.
- Included a "Scroll to Bottom" button for quick navigation.
Fixes #39
> Enhance theme and improve chat scrolling behavior

- __mocks__/stores/hfStore.ts
- src/screens/ModelsScreen/ModelCard/ModelCard.tsx
- src/screens/ModelsScreen/ModelCard/__tests__/ModelCard.test.tsx
- src/screens/ModelsScreen/ModelCard/styles.ts
- src/store/HFStore.ts
- src/store/ModelStore.ts
- src/store/__tests__/HFStore.test.ts
- src/store/defaultModels.ts
- src/utils/index.ts
- src/utils/types.ts
Added a file integrity verification check for downloaded models to ensure file consistency and help users identify corrupted downloads as opposed to model loading fails. 
- Added `checkModelFileIntegrity` utility that:
- Compares local file hash with HuggingFace's LFS hash (`lfs.oid`)
- Fetches missing file details from HF when needed (for backward compatibility)
- Compares actual file size on disk with expected size for display only
- Added visual warning when integrity check fails
> [Feat] File integrity check for downloaded models

- package.json
- yarn.lock
This PR adds -DLM_GGML_USE_CPU_AARCH64 compile definition to Android CMake build, which in turn enables runtime tensor repacking optimization for Q4_0 quantization on ARM64.
The screenshot from PocketPal's benchmarking before/after setting -DLM_GGML_USE_CPU_AARCH64:
> feat: bump llama.rn version to enable runtime repacking for Q4_0

- src/store/ModelStore.ts
Two probable race conditions were identified in the model download process:
1. Partially downloaded files could be marked as "downloaded" due to file existence checks
2. Hash calculations could occur on incomplete files, leading to incorrect integrity checks
**Solution**
Modified the download process to:
1. Track active downloads and prevent marking files as downloaded during download
2. Clear hash at download start to force recalculation
3. Only set isDownloaded and hash after confirmed successful download
Fixes #163 
Fixes #164
> Fix model download status race conditions and integrity checks

- src/store/ChatSessionStore.ts
When entering edit mode for a message, the entire chat screen would remount, causing the input state to reset. This was happening because `shouldShowHeaderDivider` computed property would change when messages were filtered in edit mode, triggering a screen options update.
Added `!isEditMode` condition to `shouldShowHeaderDivider` getter to prevent header style changes during edit mode. This ensures screen options remain stable when editing messages.
Fixes #169
> fix: correctly populate chat input text when editing the first message

- src/store/ModelStore.ts
- src/utils/index.ts
- Modified model integrity checking to prioritize file size comparison over hash verification, has for some reason `RNFS.hash` not always  return correct hash
- Added 0.1% size difference tolerance. Sufficient for detecting most corruption/incomplete download issues.
- Made hash checking a fallback option only when size comparison isn't possible
Fixes #172
> fix: use file size as first check for file integrity test, then hash

- src/components/MarkdownView/MarkdownView.tsx
- src/components/MarkdownView/styles.ts
- src/store/ModelStore.ts
- src/utils/index.ts
Models like the Deepseek R1 have a 'thinking' tag. This PR leverages this tag to render a thinking bubble.
> feat: add thinking bubble

- ios/Podfile.lock
- package.json
- yarn.lock
Sync llama.rn ->  llama.cpp [b4518](https://github.com/ggerganov/llama.cpp/releases/tag/b4518)
Fixes #176
> feat: upgrade llama.rn -> llama.cpp to support deepseek r1

- src/components/SidebarContent/SidebarContent.tsx
- src/components/SidebarContent/styles.ts
- src/store/ChatSessionStore.ts
Added a menu on top of each of session where you can select whether to rename or delete the session.
Fixes: #166 
- [ X] iOS
- [ X] Android
> feat: add session renaming functionality and context menu in sidebar

- ios/PocketPal.xcodeproj/project.pbxproj
- src/components/ChatGenerationSettingsSheet/ChatGenerationSettingsSheet.tsx
This PR fixes #211 
Additionally, it adds KeepAwakeModule files to compile sources in xcode.
> fix: use processedSettings in ChatGenerationSettingsSheet

- src/components/SidebarContent/SidebarContent.tsx
- src/components/SidebarContent/styles.ts
- src/screens/SettingsScreen/SettingsScreen.tsx
- src/store/ModelStore.ts
This PR disables Metal for iOS versions earlier than 18, as llama.cpp does not support it.
Additionally, we had to disable the sponsorship option for iOS users due to Apple's policy.
Fixes #214
> fix: disable Metal use for iOS < 18

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/pocketpalai/MainActivity.kt
- android/app/src/main/res/values/styles.xml
Previous implementation of edge-to-edge display had compatibility issues with older Android versions (<=14) and required manual configuration of system bars, fails on even older ones (<=10).
This PR replaces manual configuration with official AndroidX Activity library's `enableEdgeToEdge()` function.
Fixes #219
Fixes #222 
- Android 15 (API 35)
- Android 14 (API 34)
- Android 10 (API 29)
- Android 9 (API 28)
> Fix: Improve edge-to-edge display implementation across Android versions

- src/hooks/__tests__/useMemoryCheck.test.ts
- src/hooks/useMemoryCheck.ts
- src/hooks/useStorageCheck.ts
- src/screens/ModelsScreen/ModelCard/ModelCard.tsx
- src/utils/l10n.ts
This PR refactors the memory check logic to estimate model memory requirements using benchmark-derived parameters.
The warning criteria is now based on a simple linear fit from [AI Phone Leaderboard](https://huggingface.co/spaces/a-ghorbani/ai-phone-leaderboard) data.
Replaces the old check:
```javascript
model.size >= 0.7 * totalMemory
```
with:
```javascript
memoryRequirement >= min(totalMemory * 0.65, totalMemory - 1.2GB)
```
Where `memoryRequirement` is estimated as:
```javascript
memoryRequirement = model.size * 0.92 + 0.43
```
> refactor: improve memory requirement check with benchmark-based model

- ios/Podfile.lock
- package.json
- src/components/MarkdownView/MarkdownView.tsx
- yarn.lock
This PR adds support for rendering <thought> tags used by reasoning models like EXAONE.
Additionally, it syncs llama.rn/llama.cpp to support RWKV-7 models.
Fixes #248 
Fixes #245 (but with this caveat: https://github.com/a-ghorbani/pocketpal-ai/issues/245#issuecomment-2755997684)
> feat: add thought tag and sync llama.rn

- ios/PocketPal/Info.plist
Unlike iPhone apps, iPad apps are supposed to work with the device in any orientation including upside down. Previously, PocketPal AI was enforcing the phone-related restriction on upside down use on the iPad.
> fix(iPad): add support for upside down orientation

- src/api/__tests__/benchmark.test.ts
- src/api/__tests__/feedback.test.ts
- src/api/feedback.ts
- src/screens/AboutScreen/AboutScreen.tsx
- src/screens/AboutScreen/__tests__/AboutScreen.test.tsx
Changed the TextInput implementation to use `defaultValue` instead of `value` in the feedback component.
Removed the email from feedback.
Added a few additional tests.
> Fix(feedback): fix iOS TextInput flickering by using defaultValue prop

- src/components/ChatGenerationSettingsSheet/ChatGenerationSettingsSheet.tsx
- src/components/ChatGenerationSettingsSheet/__tests__/ChatGenerationSettingsSheet.test.tsx
- src/components/ChatGenerationSettingsSheet/styles.ts
- src/screens/BenchmarkScreen/BenchResultCard/__tests__/BenchResultCard.test.tsx
- src/screens/BenchmarkScreen/DeviceInfoCard/__tests__/DeviceInfoCard.test.tsx
- src/store/ChatSessionStore.ts
- src/store/__tests__/ChatSessionStore.test.ts
- src/store/__tests__/ModelStore.test.ts
Adds support for user-defined presets in chat completion settings.
- Presets are used as defaults for all new chats.
Also updates the UI to clearly distinguish between session and preset settings, and includes buttons to save, reset to preset, or reset to system defaults. 
Fixes #229
> Feat: add preset completion settings

- .github/workflows/ci.yml
- .github/workflows/release.yml
Fixes:
```
[Application Loader Error Output]: ERROR: [ContentDelivery.Uploader] Validation failed (409) SDK version issue. This app was built with the iOS 17.5 SDK. All iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution. (ID: 18ce17ec-6370-48c1-81c5-ef6aafe96841)
```
> fix(ci/ios): use macos-15 runner

- android/app/src/main/java/com/pocketpalai/MainActivity.kt
The app was crashing on Android when being restored from background with the following error:
```java
Caused by java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17
```
This is a known issue with `react-native-screens` where Android attempts to restore screen fragments when the app is brought back from background, which is not supported by the library.
References
[react-native-screens issue #17](https://github.com/software-mansion/react-native-screens/issues/17)
> fix(android): prevent screen fragments restoration on app resume

- src/screens/SettingsScreen/SettingsScreen.tsx
Remove the extra `ja: '日本語 (JA)',`
> chore: remove the extra ja: '日本語 (JA)',

- src/components/ChatInput/ChatInput.tsx
- src/components/ChatPalModelPickerSheet/ChatPalModelPickerSheet.tsx
Ensures CustomBackdrop is only rendered when visible, avoiding blocked touches on Android. 
This was affecting the ChatPalModelPickerSheet on the chat screen.
> fix(android): prevent backdrop from blocking interaction on chat screen

- src/components/ChatView/ChatView.tsx
- src/utils/l10n.ts
Fixes #353 
the Japanese text is translated using an LLM
> fix: add missing l10n for chat menu

- ios/Podfile.lock
- package.json
- yarn.lock
This PR syncs llama.rn -> llama.cpp to support LFM2.
Fixes #375
> feat: sync llama.rn -> llama.cpp to support LFM2

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/pocketpalai/DeviceInfoModule.kt
- ios/Podfile.lock
- src/hooks/useMemoryCheck.ts
- src/screens/BenchmarkScreen/DeviceInfoCard/DeviceInfoCard.tsx
- src/screens/SettingsScreen/SettingsScreen.tsx
- src/screens/SettingsScreen/styles.ts
- src/store/ModelStore.ts
- src/utils/deviceCapabilities.ts
- src/utils/l10n.ts
- src/utils/types.ts
This PR improves the OpenCL loading process.
**Conditional OpenCL loading:**
In `llama.rn` we only load OpenCL if i8mm and dotprod are available, so we now check for these feature to allow enabling OpenCL to prevent issues/crashes.
**Android installation fix:**
To allow installation on devices that don't provide `libOpenCL.so`, we needed to set `android:required` to false. 
```xml
<uses-native-library android:name="libOpenCL.so" android:required="false" />
```
**Code cleanup:**
All device-related checks and infos have been moved to a dedicated utility file.
> feat: refactor device checks (GPU ...) and add detailed messages for OpenCL requirements
